/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import chesscore.ClassicChessGame;
import chesscore.Move;
import chesscore.PawnPromotion;
import chesscore.Square;
import javax.swing.JFrame;

/**
 *
 * @author marlymaged
 */
public class Promotion extends javax.swing.JFrame {
Square toSquare;
Square fromSquare;
ClassicChessGame game;
JFrame frame;
    /**
     * Creates new form PawnPromotion
     */
    public Promotion(Square toSquare, Square fromSquare,ClassicChessGame game, JFrame frame) {
        this.fromSquare=fromSquare;
        this.toSquare=toSquare;
        this.game=game;
        this.frame = frame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        QueenButton = new javax.swing.JButton();
        BishopButton = new javax.swing.JButton();
        KnightButton = new javax.swing.JButton();
        RookButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Choose desired piece");

        QueenButton.setText("Queen");
        QueenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QueenButtonActionPerformed(evt);
            }
        });

        BishopButton.setText("Bishop");
        BishopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BishopButtonActionPerformed(evt);
            }
        });

        KnightButton.setText("Knight");
        KnightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KnightButtonActionPerformed(evt);
            }
        });

        RookButton.setText("Rook");
        RookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RookButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BishopButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RookButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(KnightButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(QueenButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(QueenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BishopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(KnightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RookButtonActionPerformed
  Move move=new Move(fromSquare,toSquare,PawnPromotion.Rook);
  boolean moveDone=game.makeMove(move);
  //System.out.println("Move Done? " + moveDone);
        setVisible(false);
        frame.repaint();
    }//GEN-LAST:event_RookButtonActionPerformed

    private void QueenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QueenButtonActionPerformed
 Move move=new Move(fromSquare,toSquare,PawnPromotion.Queen);
  boolean moveDone=game.makeMove(move);
  //System.out.println("Move Done? " + moveDone);
  setVisible(false);
  frame.repaint();
    }//GEN-LAST:event_QueenButtonActionPerformed

    private void BishopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BishopButtonActionPerformed
 Move move=new Move(fromSquare,toSquare,PawnPromotion.Bishop);
  boolean moveDone=game.makeMove(move);
  //System.out.println("Move Done? " + moveDone);
  setVisible(false);
  frame.repaint();
    }//GEN-LAST:event_BishopButtonActionPerformed

    private void KnightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KnightButtonActionPerformed
 Move move=new Move(fromSquare,toSquare,PawnPromotion.Knight);
  boolean moveDone=game.makeMove(move);
  //System.out.println("Move Done? " + moveDone );
  setVisible(false);
  frame.repaint();
    }//GEN-LAST:event_KnightButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BishopButton;
    private javax.swing.JButton KnightButton;
    private javax.swing.JButton QueenButton;
    private javax.swing.JButton RookButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
